import io
import re
import pandas as pd
from typing import List, Optional, Any, Union
from app.models.schema import PaperMatrixRow


class ExportService:
    @staticmethod
    def sanitize_latex(text: str) -> str:
        """Sanitizes text against Unicode artifacts, reserved LaTeX characters, and unescaped breaks."""
        if not text:
            return ""
        val = str(text)

        # 1. Strip raw internal newlines so tabular row parsing never breaks
        val = val.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")

        # 2. Convert smart/curly quotes to standard LaTeX format
        val = val.replace("“", "``").replace("”", "''")
        val = val.replace("‘", "`").replace("’", "'")

        # 3. Unicode ligatures and spaces that crash pdflatex
        val = val.replace("\u2011", "-")   # Non-breaking hyphen
        val = val.replace("\u2013", "--")  # En-dash
        val = val.replace("\u2014", "---") # Em-dash
        val = val.replace("\u202f", " ")   # Narrow no-break space
        val = val.replace("\u00a0", " ")   # Non-breaking space

        # 4. Reserved LaTeX syntax escaping (Order matters: reserved chars escaped directly)
        replacements = {
            "\\": r"\textbackslash{}",
            "&": r"\&",
            "%": r"\%",
            "$": r"\$",
            "#": r"\#",
            "_": r"\_",
            "{": r"\{",
            "}": r"\}",
            "~": r"\textasciitilde{}",
            "^": r"\textasciicircum{}",
        }

        # Safe regex mapping to avoid double-escaping
        pattern = re.compile("|".join(re.escape(k) for k in replacements.keys()))
        val = pattern.sub(lambda m: replacements[m.group(0)], val)

        # 5. Handle special non-ASCII letters AFTER reserved escaping so braces stay intact
        val = val.replace("Ł", r"{\L}").replace("ł", r"{\l}")

        # Clean multiple whitespaces
        val = re.sub(r"\s+", " ", val).strip()

        return val

    @staticmethod
    def _row_to_dict(row: Any) -> dict:
        """Safely extract dictionary from Pydantic model or raw dict."""
        if hasattr(row, "model_dump"):
            return row.model_dump()
        elif hasattr(row, "dict"):
            return row.dict()
        elif isinstance(row, dict):
            return row
        elif hasattr(row, "__dict__"):
            return row.__dict__
        return {}

    @staticmethod
    def generate_excel(rows: List[Union[PaperMatrixRow, Any]]) -> io.BytesIO:
        """Converts extracted rows to an in-memory formatted Excel document."""
        if not rows:
            df = pd.DataFrame()
        else:
            data = [ExportService._row_to_dict(r) for r in rows]
            df = pd.DataFrame(data)

        # Map default keys to publication headers if present, else title-case custom keys
        column_mapping = {
            "title": "Paper Title",
            "authors": "Authors",
            "year": "Year",
            "problem_statement": "Problem Statement / Gap",
            "methodology": "Proposed Methodology",
            "key_findings": "Key Findings / Results",
            "limitations": "Limitations",
            "future_scope": "Future Scope"
        }
        df.rename(columns={k: v for k, v in column_mapping.items() if k in df.columns}, inplace=True)
        df.columns = [str(col).replace("_", " ").title() for col in df.columns]

        output = io.BytesIO()
        with pd.ExcelWriter(output, engine="openpyxl") as writer:
            df.to_excel(writer, index=False, sheet_name="Literature Survey")

            if not df.empty:
                worksheet = writer.sheets["Literature Survey"]
                for col in worksheet.columns:
                    max_len = max(len(str(cell.value or "")) for cell in col)
                    col_letter = col[0].column_letter
                    worksheet.column_dimensions[col_letter].width = min(max(max_len + 3, 12), 45)

        output.seek(0)
        return output

    @staticmethod
    def generate_latex(rows: List[Union[PaperMatrixRow, Any]], prose: Optional[str] = None) -> io.BytesIO:
        """Converts matrix rows to academic LaTeX tabular code, bundling synthesized prose if provided."""
        latex_lines = [
            r"% ==========================================================================",
            r"% Generated by PaperMatrix AI",
            r"% QUICK START (Overleaf):",
            r"% 1. Starting a new document? Paste this entire file into main.tex and compile.",
            r"% 2. Pasting into an existing project/paper? Copy ONLY from \begin{table} to \end{table},",
            r"%    and ensure \usepackage{graphicx, geometry, array} are in your preamble.",
            r"% ==========================================================================",
            r"\documentclass{article}",
            r"\usepackage[utf8]{inputenc}",
            r"\usepackage[a4paper, margin=1in, landscape]{geometry}",
            r"\usepackage{graphicx}",
            r"\usepackage{array}",
            r"",
            r"\begin{document}",
            r""
        ]

        # Agar auto-drafted prose exist karta hai toh use Section 2 banakar add karo
        if prose and prose.strip():
            safe_prose = prose.strip()
            safe_prose = safe_prose.replace("**Related Work**", r"\section{Related Work}").replace("**Research Gaps**", r"\subsection{Identified Research Gaps}")
            safe_prose = safe_prose.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
            latex_lines.extend([
                r"\section{Literature Review \& Related Work}",
                safe_prose,
                r"\vspace{1.5em}",
                r"\subsection{Literature Survey Matrix}",
                ""
            ])

        # Standard default column sequence
        default_order = [
            "title", "authors", "year", "problem_statement",
            "methodology", "key_findings", "limitations", "future_scope"
        ]

        dict_rows = [ExportService._row_to_dict(r) for r in rows] if rows else []

        # Resolve columns preserving order and including any custom dynamic columns
        columns = []
        for k in default_order:
            if any(k in d for d in dict_rows):
                columns.append(k)

        for d in dict_rows:
            for k in d.keys():
                if k not in columns:
                    columns.append(k)

        if not columns:
            columns = default_order

        num_cols = len(columns)
        col_spec = "|".join(["p{2.5cm}" for _ in range(num_cols)])
        col_spec = f"|{col_spec}|"

        header_names = [str(col).replace("_", " ").title() for col in columns]
        escaped_headers = [ExportService.sanitize_latex(h) for h in header_names]
        header_row = " & ".join([f"\\textbf{{{h}}}" for h in escaped_headers]) + r" \\ \hline"

        latex_lines.extend([
            r"\begin{table}[htbp]",
            r"\centering",
            r"\caption{Comprehensive Literature Survey Matrix}",
            r"\label{tab:lit_survey}",
            r"\resizebox{\textwidth}{!}{%",
            f"\\begin{{tabular}}{{{col_spec}}}",
            r"\hline",
            header_row
        ])

        for d in dict_rows:
            row_cells = []
            for col in columns:
                raw_val = d.get(col, "Not explicitly stated")
                clean_val = ExportService.sanitize_latex(str(raw_val))
                row_cells.append(clean_val)
            latex_lines.append(" & ".join(row_cells) + r" \\ \hline")

        latex_lines.extend([
            r"\end{tabular}%",
            r"}",
            r"\end{table}",
            r"",
            r"\end{document}"
        ])

        output = io.BytesIO("\n".join(latex_lines).encode("utf-8"))
        output.seek(0)
        return output

    @staticmethod
    def generate_bibtex(rows: List[Union[PaperMatrixRow, Any]]) -> str:
        """Generates standard BibTeX references from matrix rows."""
        bib_entries = []
        for row in rows:
            data = ExportService._row_to_dict(row)
            title = data.get("title", "Untitled Document")
            authors = data.get("authors", "Unknown Authors")
            year = data.get("year", "N/A")

            # Clean citation key e.g. vaswani2017
            first_word = re.sub(r'[^a-zA-Z0-9]', '', str(title).split()[0].lower()) if str(title).split() else "paper"
            safe_year = re.sub(r'[^0-9]', '', str(year)) or "nd"
            cite_key = f"{first_word}_{safe_year}"

            entry = (
                f"@article{{{cite_key},\n"
                f"  title = {{{title}}},\n"
                f"  author = {{{authors}}},\n"
                f"  year = {{{year}}}\n"
                f"}}"
            )
            bib_entries.append(entry)
        return "\n\n".join(bib_entries)


export_service = ExportService()